# Generated by Django 5.1.1 on 2024-10-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geekplanet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="anime_picture",
            field=models.ImageField(blank=True, null=True, upload_to="anime_pictures/"),
        ),
    ]
