# Generated by Django 5.1.1 on 2024-10-18 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geekplanet", "0002_anime_anime_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anime",
            name="user_rating",
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
    ]
