# Generated by Django 5.1.1 on 2024-11-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geekplanet", "0003_remove_anime_user_rating_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="anime_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
