# Generated by Django 5.1.1 on 2024-11-10 01:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geekplanet", "0005_alter_anime_anime_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
